---
# vars file for dellemc.os6.os6_aaa
os6_aaa:
  tacacs_server:
        host:
          - ip: 2001:4898:f0:f09b::1001
            key: 0
            value: "abc"
            auth_port: 3
            state: present
        timeout: 6
  aaa_accounting:
        accounting:
          - accounting_type: commands
            connection_type: console
            account_mode: start-stop
            server_group: group tacacs+
            state: present
  aaa_authentication:
        login:
          - console: true
            type: group radius group tacacs+ local
            state: "present"
          - console: false
            type: group radius group tacacs+ local
            state: "present"
        re_authenticate: true
